services:
  db:
    container_name: modellink_postgres
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    security_opt:
      - apparmor=docker-restrict-db
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  db:
    driver: bridge
  modelink-network:
    external: true

volumes:
  db:
  app-volume:
  logs-volume:
  webroot:
  certs:
