const { publicUserFields } = require('./ApiFeaturesHelpersForUsers');

const allowableFields = [
    'id',
    'title',
    'desc',
    'status',
    'galleryImages',
    'tags',
    'views',
    'sales',
    'totalStars',
    'starFrequency',
    'reviewCount',
    'avgRating',
    'featured',
    'reviewCountRule',
    'createdAt',
    'updatedAt',
    'developerId',
    'categoryId',

    'categoryRel.id',
    'categoryRel.name',
    'categoryRel.slug',

    'developer.id',
    'developer.first_name',
    'developer.last_name',
    'developer.email',
    'developer.org_username',
    'developer.avatar',
    'developer.org_name',
    'developer.org_desc',
    'developer.country',
    'developer.isVerified',

    'versions.id',
    'versions.version',
    'versions.isActive',
    'versions.isPrimary',
    'versions.price',
    'versions.modality',
    'versions.bodyPart',
    'versions.indications',
    'versions.fda',
    'versions.fdaUrl',
    'versions.deliveryTime',
    'versions.createdAt',
    'versions.modalityId',
    'versions.bodyPartId',
    'versions.modalityRel.name',
    'versions.bodyPartRel.name',
    'versions.priceRule',
    'versions.deliveryTimeRule',
    'versions.features.feature',
    'versions.metrics.metric',
];

const defaultSort = { updatedAt: 'desc' };

const exactMatchFields = [
    'id',
    'status',
    'developerId',
    'categoryId',
    'views',
    'versions.id',
    'versions.isActive',
    'versions.isPrimary',
    'versions.fda',
    'versions.price',
    'versions.deliveryTime',
    'versions.modalityId',
    'versions.bodyPartId',
    'versions.modality',
    'versions.bodyPart',
    'versions.features.feature',
    'versions.metrics.metric',
    'categoryRel.name',
    'categoryRel.slug',
    'developer.isVerified',
    'featured',
    'tags',
];

const searchFields = [
    'title',
    'desc',
    'categoryRel.name',
    'developer.org_username',
    'developer.first_name',
    'developer.last_name',
    'developer.email',
    'developer.org_name',
    'versions.indications',
];

const fieldConfigs = {
    id: 'integer',
    categoryId: 'integer',
    sales: 'integer',
    views: 'integer',
    totalStars: 'integer',
    starFrequency: 'integer',
    reviewCount: 'integer',
    avgRating: 'float',
    featured: 'boolean',
    'versions.id': 'integer',
    'versions.modalityId': 'integer',
    'versions.bodyPartId': 'integer',
    versions: 'relation-array',
    tags: 'array-primitive',
    galleryImages: 'array-primitive',
    'versions.price': 'integer',
    'versions.deliveryTime': 'integer',
    'versions.features': 'relation-array',
    'versions.metrics': 'relation-array',
    developer: 'relation-object',
};

exports.generateModelOptions = () => ({
    defaultRelations: {
        categoryRel: { select: { id: true, name: true, slug: true, parentId: true } },
        developer: {
            select: publicUserFields,
        },
        versions: {
            where: {
                isActive: true,
            },
            include: {
                features: true,
                metrics: true,
                modalityRel: { select: { id: true, name: true, slug: true } },
                bodyPartRel: { select: { id: true, name: true, slug: true } },
            },
        },
    },
    defaultSort,
    defaultLimit: 12,
    allowableFields,
    exactMatchFields,
    fieldConfigs,
    searchFields,
});
